volumes:
  postgres_data:
  static:

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env

  backend:
    build: .
    volumes:
      - static:/backend_static
    env_file: .env
    depends_on:
      - db

  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles/
    depends_on:
      - backend